import {
	IMPERIAL_UNITS,
	METRIC_UNITS,
	SPINDLE_MODES,
	SPIRAL_MOVEMENT,
	START_POSITION_BACK_LEFT,
	START_POSITION_BACK_RIGHT,
	START_POSITION_CENTER,
	START_POSITION_FRONT_LEFT,
	START_POSITION_FRONT_RIGHT,
	SURFACING_DWELL_DURATION,
	ZIG_ZAG_MOVEMENT,
} from "app/constants";
import controller from "app/lib/controller";
import defaultState from "app/store/defaultState";
import reduxStore from "app/store/redux";

import { convertToImperial } from "../../Preferences/calculate";

const [M3] = SPINDLE_MODES;

export default class Generator {
	constructor({ surfacing, units }) {
		this.surfacing = surfacing;
		this.units = units;
	}

	/**
	 * Main function to generate gcode
	 */
	generate = ({ returnArray = false } = {}) => {
		const defaultSurfacingState = get(
			defaultState,
			"workspace.widgets.surfacing",
		);

		const { surfacing, units, generateGcode, getSafeZValue } = this;
		const {
			skimDepth,
			maxDepth,
			feedrate,
			spindleRPM,
			spindle = M3,
			shouldDwell,
			mist,
			flood,
		} = { ...defaultSurfacingState, ...surfacing };

		const z = getSafeZValue();

		const dwell = shouldDwell ? [`G04 P${SURFACING_DWELL_DURATION}`] : [];
		const m7 = mist ? ["M7"] : [];
		const m8 = flood ? ["M8"] : [];
		const setUnits =
			{
				[METRIC_UNITS]: "G21 ;mm",
				[IMPERIAL_UNITS]: "G20 ;inches",
			}[units] ?? "G21 ;mm";

		const depth = skimDepth;
		const gcodeArr = [
			"(Header)",
			"(Generated by gSender from Sienci Labs)",
			setUnits,
			"G90",
			`${spindle} S${spindleRPM}`,
			...dwell,
			"G0 X0 Y0",
			`G0 Z${z}`,
			...m7,
			...m8,
			`G1 F${feedrate}`,
			"(Header End)",
			"\n",
		];

		function processGcode(arr, depth, count, maxDepth) {
			const gcodeLayer = generateGcode({
				depth: depth < maxDepth ? depth : maxDepth,
				count,
			});
			arr.push(...gcodeLayer);

			if (depth >= maxDepth) {
				return arr;
			}

			return processGcode(arr, depth + skimDepth, count + 1, maxDepth);
		}

		const processedGcode = processGcode([], depth, 1, maxDepth);

		gcodeArr.push(...processedGcode);

		const m9 = mist || flood ? ["M9 ;Turn off Coolant"] : [];

		gcodeArr.push(
			"(Footer)",
			...m9,
			"M5 ;Turn off spindle",
			...dwell,
			"(End of Footer)",
		);

		if (returnArray) {
			return gcodeArr;
		}

		//Convert to string for interpretation
		const gcodeArrStr = gcodeArr.join("\n");

		return gcodeArrStr;
	};

	/**
	 * Function to generate gcode array
	 * @param {number} depth - Depth value for Z axis
	 * @param {number} count - Count value keeping track of the number of layers
	 * @returns {array} - Returns the generated gcode set in an array
	 */
	generateGcode = ({ depth, count }) => {
		const {
			bitDiameter,
			stepover,
			length,
			width,
			maxDepth,
			startPosition,
			type,
			cutDirectionFlipped,
			skimDepth,
			mist,
			flood,
		} = this.surfacing;

		const stepoverPercentage = stepover > 80 ? 80 / 100 : stepover / 100;

		const stepoverAmount = this.toFixedValue(bitDiameter * stepoverPercentage);

		const DEFAULT_FACTOR = { x: 1, y: -1 };

		const axisFactors =
			{
				[START_POSITION_BACK_LEFT]: { x: 1, y: -1 },
				[START_POSITION_BACK_RIGHT]: { x: -1, y: -1 },
				[START_POSITION_FRONT_LEFT]: { x: 1, y: 1 },
				[START_POSITION_FRONT_RIGHT]: { x: -1, y: 1 },
				[START_POSITION_CENTER]: DEFAULT_FACTOR,
			}[startPosition] ?? DEFAULT_FACTOR;

		const options = {
			depth,
			length,
			width,
			count,
			stepoverAmount,
			maxDepth,
			axisFactors,
			cutDirectionFlipped,
			startPosition,
		};

		const executeSurfacing = {
			[SPIRAL_MOVEMENT]: this.generateSpiral,
			[ZIG_ZAG_MOVEMENT]: this.generateZigZag,
		}[type];

		const gcodeArr = executeSurfacing(options);

		const safeHeight = this.getSafeZValue();
		const zValue = this.toFixedValue(safeHeight - (depth - skimDepth));
		const startPosGcode =
			count === 1
				? []
				: [
						"(Move to Starting Height)",
						`G0 Z${zValue}`,
						"(End of Move to Starting Height)",
						"",
					];

		return [
			`(*** Layer ${count} ***)`,
			...startPosGcode,
			...gcodeArr,
			`(*** End of Layer ${count} ***)`,
			"\n",
		];
	};

	toFixedValue(value = 0, amount = 3) {
		return Number(value.toFixed(amount));
	}

	rampIntoMaterial = (direction = { axis: "Y", factor: 1 }) => {
		const RAMP_ANGLE_DEGREES = 2;
		const MAX_ZIGZAG_LENGTH_MM = 150;

		const { axis, factor } = direction;
		const { skimDepth, bitDiameter, width, length } = this.surfacing;
		const units = store.get("workspace.units");
		const safeHeight = this.getSafeZValue();

		const totalZDrop = safeHeight + Math.abs(skimDepth);

		// Zigzag length: min surface dimension minus one full bit diameter (to stay within bounds),
		// capped at `MAX_ZIGZAG_LENGTH_MM` so the ramp doesn't span the entire workpiece on large jobs.
		const minDimension = Math.min(Math.abs(width), Math.abs(length));
		const maxZigzagLength =
			units === METRIC_UNITS
				? MAX_ZIGZAG_LENGTH_MM
				: convertToImperial(MAX_ZIGZAG_LENGTH_MM);

		const zigzagLength = Math.max(
			bitDiameter,
			Math.min(minDimension - bitDiameter, maxZigzagLength),
		);

		const zPerLeg =
			zigzagLength * Math.tan((RAMP_ANGLE_DEGREES * Math.PI) / 180);

		// Use an even number of legs so the tool returns to the start XY position after ramping
		const numLegsRaw = Math.ceil(totalZDrop / zPerLeg);
		const numLegs = numLegsRaw % 2 === 0 ? numLegsRaw : numLegsRaw + 1;

		// Spread the total Z drop evenly across all legs (keeps angle at or below `RAMP_ANGLE_DEGREES`)
		const actualZPerLeg = Number((totalZDrop / numLegs).toFixed(3));
		const rampingArr = ["(Ramping into Material)", "G91"];

		for (let i = 0; i < numLegs; i++) {
			// Switch direction on each leg to create a zigzag pattern
			const legFactor = i % 2 === 0 ? factor : factor * -1;

			rampingArr.push(
				`G1 ${axis}${Number((zigzagLength * legFactor).toFixed(3))} Z${-actualZPerLeg}`,
			);
		}

		rampingArr.push("G90", "(End of Ramping into Material)", "");

		return rampingArr;
	};

	drawInitialPerimeter = (
		x,
		y,
		z,
		direction,
		shouldZeroAxisZ = true,
		startPosition,
		cutDirectionFlipped,
	) => {
		const enterMaterial = this.rampIntoMaterial(direction);

		let mainPerimeterArea = [
			"G91",
			`G1 Y${Math.abs(y) * -1}`,
			`G1 X${Math.abs(x)}`,
			`G1 Y${Math.abs(y)}`,
			`G1 X${Math.abs(x) * -1}`,
			"G90",
		];

		if (startPosition !== START_POSITION_CENTER) {
			mainPerimeterArea = cutDirectionFlipped
				? [`G1 X${x}`, `G1 Y${y}`, "G1 X0", "G1 Y0"]
				: [`G1 Y${y}`, `G1 X${x}`, "G1 Y0", "G1 X0"];
		}

		return [
			"(Covering Surfacing Perimeter)",
			...enterMaterial,
			...mainPerimeterArea,
			...(shouldZeroAxisZ ? ["G1 Z0"] : []),
			"(End of Covering Surfacing Perimeter)",
			"",
		];
	};

	enterSpiralStartArea(
		x,
		y,
		singleMovement = false,
		movementType = "G0",
		lastAxis = "X",
	) {
		const movement = [];

		const X = x ? "X" + x : undefined;
		const Y = y ? "Y" + y : undefined;

		if (singleMovement) {
			if (lastAxis === "X") {
				movement.push(`${movementType} ${Y || ""} ${X || ""}`.trim());
			}

			if (lastAxis === "Y") {
				movement.push(`${movementType} ${X || ""} ${Y || ""}`.trim());
			}
		} else {
			if (lastAxis === "X") {
				if (Y) {
					movement.push(`${movementType} ${Y}`);
				}
				if (X) {
					movement.push(`${movementType} ${X}`);
				}
			}

			if (lastAxis === "Y") {
				if (X) {
					movement.push(`${movementType} ${X}`);
				}
				if (Y) {
					movement.push(`${movementType} ${Y}`);
				}
			}
		}

		return [
			"(Entering Start Position)",
			"G91",
			...movement,
			"G90",
			"(End of Entering Start Position)",
			"",
		];
	}

	getSafeZValue() {
		const workspaceUnits = store.get("workspace.units");
		const zVal = workspaceUnits === METRIC_UNITS ? 3 : 0.12;

		return zVal;
	}

	returnToZero = () => {
		const z = this.getSafeZValue();

		return [
			"(Returning to Zero)",
			`G0 Z${z}`,
			"G0 X0 Y0",
			"(End of Returning to Zero)",
			"",
		];
	};

	generateSpiral = (options) => {
		const {
			drawInitialPerimeter,
			enterSpiralStartArea,
			drawSpiral,
			returnToZero,
			toFixedValue,
		} = this;
		const {
			depth,
			length,
			width,
			axisFactors,
			stepoverAmount,
			cutDirectionFlipped,
			startPosition,
		} = options;
		const { x: xFactor, y: yFactor } = axisFactors;
		const startIsInCenter = startPosition === START_POSITION_CENTER;

		const x = toFixedValue(width * xFactor);
		const y = toFixedValue(length * yFactor);
		const z = toFixedValue(depth * -1);

		const halfOfLength = toFixedValue(length / 2);
		const halfOfWidth = toFixedValue(width / 2);

		const startPos = {
			x: cutDirectionFlipped ? 0 : toFixedValue(stepoverAmount),
			y: cutDirectionFlipped
				? toFixedValue(stepoverAmount * 2)
				: toFixedValue(stepoverAmount),
		};

		const endPos = {
			x: toFixedValue(width - stepoverAmount),
			y: toFixedValue(length - stepoverAmount),
		};

		const direction = {
			axis: "Y",
			factor: axisFactors.y,
		};

		if (width >= length) {
			direction.axis = "X";
			direction.factor = axisFactors.x;
		}

		function getNewStartPos(startPos) {
			return {
				x: toFixedValue(startPos.x + stepoverAmount),
				y: toFixedValue(startPos.y + stepoverAmount),
			};
		}

		function getNewEndPos(endPos) {
			return {
				x: toFixedValue(endPos.x - stepoverAmount),
				y: toFixedValue(endPos.y - stepoverAmount),
			};
		}

		function exitCondition(startPos, endPos) {
			// Exit when positions actually cross (not just close)
			const shouldExit = endPos.x < startPos.x || endPos.y < startPos.y;
			return shouldExit;
		}

		function processGcode(
			startPos,
			endPos,
			prevStartPos,
			prevEndPos,
			xFactor,
			yFactor,
		) {
			const arr = [];

			const xValueStart = startIsInCenter
				? toFixedValue((halfOfWidth - endPos.x) * xFactor)
				: toFixedValue(endPos.x * xFactor);
			const yValueStart = startIsInCenter
				? toFixedValue((halfOfLength - endPos.y) * yFactor)
				: toFixedValue(endPos.y * yFactor);
			const xValueEnd = startIsInCenter
				? toFixedValue((halfOfWidth - (startPos.x + stepoverAmount)) * xFactor)
				: toFixedValue((startPos.x + stepoverAmount) * xFactor);
			const yValueEnd = startIsInCenter
				? toFixedValue((halfOfLength - startPos.y) * yFactor)
				: toFixedValue(startPos.y * yFactor);

			if (cutDirectionFlipped) {
				if (endPos.x >= startPos.x) {
					arr.push(`G1 X${xValueStart}`);

					if (length >= width) {
						arr.push(`G1 Y${yValueStart}`);
						// Always add the final X movement if we're moving in the X direction
						arr.push(`G1 X${xValueEnd}`);
					}

					if (endPos.y >= startPos.y) {
						if (width > length) {
							arr.push(`G1 Y${yValueStart}`, `G1 X${xValueEnd}`);
						}

						arr.push(`G1 Y${yValueEnd}`);
					}
				}
			} else {
				// Add movements based on the spiral pattern
				if (endPos.y >= startPos.y) {
					arr.push(`G1 Y${yValueStart}`);

					if (width >= length) {
						// For wider than long rectangles, complete the Y movement first
						arr.push(`G1 X${xValueStart}`, `G1 Y${yValueEnd}`);
					}
				} else {
					// If Y positions have crossed, still add the final Y movement to complete the pattern
					arr.push(`G1 Y${yValueStart}`);
				}

				if (endPos.x >= startPos.x) {
					if (length > width) {
						// For longer than wide rectangles, complete the X movement first
						arr.push(`G1 X${xValueStart}`, `G1 Y${yValueEnd}`);
					}
					// Add the final X movement to complete the spiral
					if (endPos.y < startPos.y) {
						// If Y positions have crossed, use xValueStart to complete the spiral properly
						arr.push(`G1 X${xValueStart}`);
					} else {
						// Normal spiral movement
						arr.push(`G1 X${xValueEnd}`);
					}
				}
			}

			arr.push("");

			return arr;
		}

		const initialPerimeter = drawInitialPerimeter(
			x,
			y,
			z,
			direction,
			false,
			startPosition,
			cutDirectionFlipped,
		);
		const spirals = drawSpiral(
			[],
			startPos,
			endPos,
			startPos,
			endPos,
			options,
			processGcode,
			exitCondition,
			getNewStartPos,
			getNewEndPos,
		);
		const returnToStart = returnToZero();
		const spiralStartArea = enterSpiralStartArea(
			stepoverAmount * xFactor,
			stepoverAmount * yFactor,
			false,
			"G1",
			direction.axis,
		);

		const toolpath = new Toolpath();
		toolpath.loadFromStringSync(spirals.join("\n"));
		const position = toolpath.getPosition();

		const mainSpiralArea = [];

		const startFromCenterPerimeter = drawInitialPerimeter(
			width,
			length,
			z,
			direction,
			false,
			startPosition,
		);

		const startFromCenterPerimeterPosition = [
			"(Entering Perimeter Start Position)",
			`G0 X${halfOfWidth * -1} Y${halfOfLength}`,
			"(End of Entering Perimeter Start Position)",
			"",
		];

		const safeHeight = this.getSafeZValue();
		const zValue = toFixedValue(
			safeHeight - (depth - this.surfacing.skimDepth),
		);
		const startFromCenterStartPosition = [
			"(Entering Start Position)",
			`G0 X${position.x} Y${position.y}`,
			`G0 Z${zValue} ; Start Pos - (Curr Depth - Cut Depth)`,
			"G91",
			`G0 Z${Math.abs(depth) * -1 - safeHeight}`,
			"G90",
			"(End of Entering Start Position)",
			"",
		];

		if (startIsInCenter) {
			mainSpiralArea.push(
				...startFromCenterPerimeterPosition,
				...startFromCenterPerimeter,
				...startFromCenterStartPosition,
				...spirals.reverse(),
			);
		} else {
			mainSpiralArea.push(...spirals);
		}

		const remainderXFactor = cutDirectionFlipped ? 1 : -1;
		const remainderYFactor = cutDirectionFlipped ? -1 : 1;
		const remainder = cutDirectionFlipped
			? [
					"",
					"(Cover Remaining Area)",
					`G1 Y${toFixedValue(Math.abs(halfOfLength - stepoverAmount) * remainderYFactor)}`,
					`G1 X${toFixedValue(Math.abs(halfOfWidth - stepoverAmount) * remainderXFactor * -1)}`,
					`G1 X${toFixedValue(Math.abs(halfOfWidth - stepoverAmount) * remainderXFactor)}`,
					`G1 Y${toFixedValue(Math.abs(halfOfLength) * remainderXFactor * -1)}`,
					"(End of Cover Remaining Area)",
					"",
				]
			: [
					"",
					"(Cover Remaining Area)",
					`G1 X${toFixedValue(Math.abs(halfOfWidth - stepoverAmount) * remainderXFactor * -1)}`,
					`G1 Y${toFixedValue(Math.abs(halfOfLength) * -remainderYFactor)}`,
					"(End of Cover Remaining Area)",
					"",
				];

		/**
		 * 1. Draw initial surfacing area perimeter
		 * 2. Move to the start area
		 * 3. Begin drawing spiral recursively
		 * 4. End of spiral, move z axis up and return to the zero position
		 **/
		const gcodeArr = startIsInCenter
			? [...mainSpiralArea.flat(), ...remainder, ...returnToStart]
			: [
					...initialPerimeter,
					...spiralStartArea,
					...mainSpiralArea.flat(),
					...returnToStart,
				];

		return gcodeArr;
	};

	drawSpiral = (
		arr,
		startPos,
		endPos,
		prevStartPos,
		prevEndPos,
		options,
		processGcode,
		exitCondition,
		getNewStartPos,
		getNewEndPos,
	) => {
		const { drawSpiral } = this;
		const { axisFactors } = options;
		const { x: xFactor, y: yFactor } = axisFactors;

		arr.push(
			...processGcode(
				startPos,
				endPos,
				prevStartPos,
				prevEndPos,
				xFactor,
				yFactor,
			),
		);

		if (exitCondition(startPos, endPos)) {
			return arr;
		}

		const nextStartPos = getNewStartPos(startPos);
		const nextEndPos = getNewEndPos(endPos);

		return drawSpiral(
			arr,
			nextStartPos,
			nextEndPos,
			startPos,
			endPos,
			options,
			processGcode,
			exitCondition,
			getNewStartPos,
			getNewEndPos,
		);
	};

	generateZigZag = (options) => {
		const {
			depth,
			length,
			width,
			axisFactors,
			stepoverAmount,
			cutDirectionFlipped,
			startPosition,
		} = options;
		const { x: xFactor, y: yFactor } = axisFactors;
		const {
			toFixedValue,
			drawInitialPerimeter,
			drawZigZag,
			returnToZero,
			rampIntoMaterial,
		} = this;
		const startIsInCenter = startPosition === START_POSITION_CENTER;

		const x = toFixedValue(width * xFactor);
		const y = toFixedValue(length * yFactor);
		const z = toFixedValue(depth * -1);

		const startPos = {
			x: cutDirectionFlipped ? toFixedValue(stepoverAmount) : width,
			y: cutDirectionFlipped ? length : toFixedValue(stepoverAmount),
		};

		const endPos = {
			x: cutDirectionFlipped ? toFixedValue(stepoverAmount * 2) : 0,
			y: cutDirectionFlipped ? 0 : toFixedValue(stepoverAmount * 2),
		};

		const direction = {
			axis: "Y",
			factor: axisFactors.y,
		};

		if (width > length) {
			direction.axis = "X";
			direction.factor = axisFactors.x;
		}

		function exitCondition(startPos, endPos) {
			return cutDirectionFlipped ? startPos.x >= width : startPos.y >= length;
		}

		function getNewStartPos(startPos, endPos) {
			if (cutDirectionFlipped) {
				return {
					x: toFixedValue(endPos.x + stepoverAmount),
					y: startPos.y,
				};
			}

			return {
				x: startPos.x,
				y: toFixedValue(endPos.y + stepoverAmount),
			};
		}

		function getNewEndPos(endPos) {
			if (cutDirectionFlipped) {
				return {
					x: toFixedValue(endPos.x + stepoverAmount * 2),
					y: endPos.y,
				};
			}

			return {
				x: endPos.x,
				y: toFixedValue(endPos.y + stepoverAmount * 2),
			};
		}

		function processGcode(startPos, endPos, xFactor, yFactor) {
			const arr = [];

			const halfOfLength = toFixedValue(length / 2);
			const halfOfWidth = toFixedValue(width / 2);

			if (startIsInCenter) {
				if (cutDirectionFlipped) {
					if (
						startPos.x - halfOfWidth > halfOfWidth &&
						endPos.x - halfOfWidth > halfOfWidth &&
						startPos.y - halfOfLength <= halfOfLength &&
						endPos.y - halfOfLength <= halfOfLength
					) {
						arr.push(`G1 Y${toFixedValue(halfOfLength) * -1}`, "");
						return arr;
					}

					if (startPos.y - halfOfLength <= halfOfLength) {
						arr.push(`G1 Y${toFixedValue(halfOfLength) * -1}`);
					}

					if (startPos.x - halfOfWidth <= halfOfWidth) {
						arr.push(`G1 X${toFixedValue(halfOfWidth * -1 + startPos.x)}`);
					}

					if (endPos.y - halfOfLength <= halfOfLength) {
						arr.push(`G1 Y${toFixedValue(halfOfLength)}`);
					}

					if (endPos.x - halfOfWidth <= halfOfWidth) {
						arr.push(`G1 X${toFixedValue(halfOfWidth * -1 + endPos.x)}`);
					}
				} else {
					if (startPos.y - halfOfLength <= halfOfLength) {
						arr.push(
							`G1 Y${toFixedValue(halfOfLength - startPos.y)}`,
							`G1 X${toFixedValue(halfOfWidth)}`,
						);
					}

					if (endPos.y - halfOfLength <= halfOfLength) {
						arr.push(
							`G1 Y${toFixedValue(halfOfLength - endPos.y)}`,
							`G1 X${toFixedValue(halfOfWidth) * -1}`,
						);
					}
				}

				arr.push("");

				return arr;
			}

			if (cutDirectionFlipped) {
				if (startPos.x <= width) {
					arr.push(
						`G1 X${toFixedValue(startPos.x * xFactor)}`,
						`G1 Y${toFixedValue(startPos.y * yFactor)}`,
					);
				}

				if (endPos.x <= width) {
					arr.push(
						`G1 X${toFixedValue(endPos.x * xFactor)}`,
						`G1 Y${toFixedValue(endPos.y * yFactor)}`,
					);
				}
			} else {
				if (startPos.y <= length) {
					arr.push(
						`G1 Y${toFixedValue(startPos.y * yFactor)}`,
						`G1 X${toFixedValue(startPos.x * xFactor)}`,
					);
				}

				if (endPos.y <= length) {
					arr.push(
						`G1 Y${toFixedValue(endPos.y * yFactor)}`,
						`G1 X${toFixedValue(endPos.x * xFactor)}`,
					);
				}
			}

			arr.push("");

			return arr;
		}

		const initialPerimeter = drawInitialPerimeter(x, y, z, direction, false);
		const spirals = drawZigZag(
			[],
			startPos,
			endPos,
			options,
			processGcode,
			exitCondition,
			getNewStartPos,
			getNewEndPos,
		);
		const returnToStart = returnToZero();

		const startArea = [
			"(Entering Start Area)",
			`G0 X${toFixedValue(width / 2) * -1} Y${toFixedValue(length / 2)}`,
			"(End of Entering Start Area)",
		];

		const startFromCenterPerimeter = [
			"(Drawing Perimeter)",
			`G0 X${toFixedValue((width / 2) * -1)}`,
			`G0 Y${toFixedValue(length / 2)}`,

			`G1 Y${toFixedValue(length / 2) * -1}`,
			`G1 X${toFixedValue(width / 2)}`,
			`G1 Y${toFixedValue(length / 2)}`,
			`G1 X${toFixedValue(width / 2) * -1}`,
			"(End of Drawing Perimeter)",
			"",
		];

		/**
		 * 1. Draw initial surfacing area perimeter and do not zero z axis
		 * 2. Begin drawing zig zag recursively
		 * 4. End of zig zag, move z axis up and return to the zero position
		 **/
		const gcodeArr = startIsInCenter
			? [
					...startArea,
					...rampIntoMaterial(direction),
					...startFromCenterPerimeter,
					...spirals,
					...returnToStart,
				]
			: [...initialPerimeter, ...spirals, ...returnToStart];

		return gcodeArr;
	};

	drawZigZag = (
		arr,
		startPos,
		endPos,
		options,
		processGcode,
		exitCondition,
		getNewStartPos,
		getNewEndPos,
	) => {
		const { axisFactors } = options;
		const { x: xFactor, y: yFactor } = axisFactors;
		const { drawZigZag } = this;

		arr.push(...processGcode(startPos, endPos, xFactor, yFactor));

		if (exitCondition(startPos, endPos)) {
			return arr;
		}

		const nextStartPos = getNewStartPos(startPos, endPos);
		const nextEndPos = getNewEndPos(endPos);

		return drawZigZag(
			arr,
			nextStartPos,
			nextEndPos,
			options,
			processGcode,
			exitCondition,
			getNewStartPos,
			getNewEndPos,
		);
	};
}
