export const GRBL_SETTINGS_INPUT_TYPES = {
    NUMBER: 'number',
    AXIS_MASK: 'axis-mask',
    MASK_STATUS_REPORT: 'mask-status-report',
    SWITCH: 'switch',
};

const { NUMBER, AXIS_MASK, MASK_STATUS_REPORT, SWITCH } =
    GRBL_SETTINGS_INPUT_TYPES;

// Settings
// https://github.com/gnea/grbl/blob/master/doc/csv/setting_codes_en_US.csv
export const GRBL_SETTINGS = [
    {
        setting: '$0',
        message: 'Step pulse time',
        category: 'Motors',
        units: 'μs',
        description: 'Sets time length per step. Minimum 3usec.',
        inputType: NUMBER,
        min: 0,
        max: 20,
        step: 1,
    },
    {
        setting: '$1',
        message: 'Step idle delay',
        category: 'Motors',
        units: 'ms',
        description:
            'Sets a short hold delay when stopping to let dynamics settle before disabling steppers. Value 255 keeps motors enabled with no delay.',
        inputType: NUMBER,
        min: 25,
        max: 255,
        step: 5,
    },
    {
        setting: '$2',
        message: 'Step pulse invert',
        category: 'Motors',
        units: 'mask',
        description:
            'Inverts the step signal. Set axis bit to invert (00000ZYX).',
        inputType: AXIS_MASK,
    },
    {
        setting: '$3',
        message: 'Step direction invert',
        category: 'Motors',
        units: 'mask',
        description:
            'Inverts the direction signal. Set axis bit to invert (00000ZYX).',
        inputType: AXIS_MASK,
    },
    {
        setting: '$4',
        message: 'Invert step enable pin',
        category: 'Pins',
        units: 'boolean',
        description: 'Inverts the stepper driver enable pin signal.',
        inputType: SWITCH,
    },
    {
        setting: '$5',
        message: 'Invert limit pins',
        category: 'Pins',
        units: 'boolean',
        description: 'Inverts the all of the limit input pins.',
        inputType: SWITCH,
    },
    {
        setting: '$6',
        message: 'Invert probe pin',
        category: 'Pins',
        units: 'boolean',
        description: 'Inverts the probe input pin signal.',
        inputType: SWITCH,
    },
    {
        setting: '$10',
        message: 'Status report options',
        category: 'GRBL',
        units: 'mask',
        description: 'Alters data included in status reports.',
        inputType: MASK_STATUS_REPORT,
    },
    {
        setting: '$11',
        message: 'Junction deviation',
        category: 'GRBL',
        units: 'mm',
        description:
            'Sets how fast Grbl travels through consecutive motions. Lower value slows it down.',
        inputType: NUMBER,
        min: 0.001,
        step: 0.001,
    },
    {
        setting: '$12',
        message: 'Arc tolerance',
        category: 'GRBL',
        units: 'mm',
        description:
            'Sets the G2 and G3 arc tracing accuracy based on radial error. Beware: A very small value may effect performance.',
        inputType: NUMBER,
        min: 0.001,
        step: 0.001,
    },
    {
        setting: '$13',
        message: 'Report in inches',
        category: 'GRBL',
        units: 'boolean',
        description:
            'Enables inch units when returning any position and rate value that is not a settings value.',
        inputType: SWITCH,
    },
    {
        setting: '$20',
        message: 'Soft limits enable',
        category: 'Homing',
        units: 'boolean',
        description:
            'Enables soft limits checks within machine travel and sets alarm when exceeded. Requires homing.',
        inputType: SWITCH,
    },
    {
        setting: '$21',
        message: 'Hard limits enable',
        category: 'Homing',
        units: 'boolean',
        description:
            'Enables hard limits. Immediately halts motion and throws an alarm when switch is triggered.',
        inputType: SWITCH,
    },
    {
        setting: '$22',
        message: 'Homing cycle enable',
        category: 'Homing',
        units: 'boolean',
        description:
            'Enables homing cycle. Requires limit switches on all axes.',
        inputType: SWITCH,
    },
    {
        setting: '$23',
        message: 'Homing direction invert',
        category: 'Homing',
        units: 'mask',
        description:
            'Homing searches for a switch in the positive direction. Set axis bit (00000ZYX) to search in negative direction.',
        inputType: AXIS_MASK,
    },
    {
        setting: '$24',
        message: 'Homing locate feed rate',
        category: 'Homing',
        units: 'mm/min',
        description:
            'Feed rate to slowly engage limit switch to determine its location accurately.',
        inputType: NUMBER,
        min: 1,
        step: 1,
    },
    {
        setting: '$25',
        message: 'Homing search seek rate',
        category: 'Homing',
        units: 'mm/min',
        description:
            'Seek rate to quickly find the limit switch before the slower locating phase.',
        inputType: NUMBER,
        min: 100,
        step: 100,
    },
    {
        setting: '$26',
        message: 'Homing switch debounce delay',
        category: 'Homing',
        units: 'ms',
        description:
            'Sets a short delay between phases of homing cycle to let a switch debounce.',
        inputType: NUMBER,
        min: 5,
        max: 255,
        step: 5,
    },
    {
        setting: '$27',
        message: 'Homing switch pull-off distance',
        category: 'Homing',
        units: 'mm',
        description:
            "Retract distance after triggering switch to disengage it. Homing will fail if switch isn't cleared.",
        inputType: NUMBER,
        min: 0,
        step: 0.5,
    },
    {
        setting: '$30',
        message: 'Maximum spindle speed',
        category: 'Spindle',
        units: 'rpm',
        description: 'Maximum spindle speed. Sets PWM to 100% duty cycle.',
        inputType: NUMBER,
        min: 100,
        step: 100,
    },
    {
        setting: '$31',
        message: 'Minimum spindle speed',
        category: 'Spindle',
        units: 'rpm',
        description:
            'Minimum spindle speed. Sets PWM to 0.4% or lowest duty cycle.',
        inputType: NUMBER,
        min: 1,
        step: 1,
    },
    {
        setting: '$32',
        message: 'Laser-mode enabled as spindle',
        category: 'Spindle',
        units: 'boolean',
        description:
            'Converts spindle commands into laser mode. Consecutive G1/2/3 commands will not halt when spindle speed is changed.',
        inputType: SWITCH,
    },
    {
        setting: '$100',
        message: 'X-axis travel resolution',
        category: 'Motors',
        units: 'step/mm',
        description: 'X-axis travel resolution in steps per millimeter.',
        inputType: NUMBER,
        min: 10,
        step: 10,
    },
    {
        setting: '$101',
        message: 'Y-axis travel resolution',
        category: 'Motors',
        units: 'step/mm',
        description: 'Y-axis travel resolution in steps per millimeter.',
        inputType: NUMBER,
        min: 10,
        step: 10,
    },
    {
        setting: '$102',
        message: 'Z-axis travel resolution',
        category: 'Motors',
        units: 'step/mm',
        description: 'Z-axis travel resolution in steps per millimeter.',
        inputType: NUMBER,
        min: 10,
        step: 10,
    },
    {
        setting: '$110',
        message: 'X-axis maximum rate',
        category: 'Motors',
        units: 'mm/min',
        description: 'X-axis maximum rate. Used as G0 rapid rate.',
        inputType: NUMBER,
        min: 100,
        step: 100,
    },
    {
        setting: '$111',
        message: 'Y-axis maximum rate',
        category: 'Motors',
        units: 'mm/min',
        description: 'Y-axis maximum rate. Used as G0 rapid rate.',
        inputType: NUMBER,
        min: 100,
        step: 100,
    },
    {
        setting: '$112',
        message: 'Z-axis maximum rate',
        category: 'Motors',
        units: 'mm/min',
        description: 'Z-axis maximum rate. Used as G0 rapid rate.',
        inputType: NUMBER,
        min: 10,
        step: 10,
    },
    {
        setting: '$120',
        message: 'X-axis acceleration',
        category: 'Motors',
        units: 'mm/sec^2',
        description:
            'X-axis acceleration. Used for motion planning to not exceed motor torque and lose steps.',
        inputType: NUMBER,
        min: 1,
        step: 10,
    },
    {
        setting: '$121',
        message: 'Y-axis acceleration',
        category: 'Motors',
        units: 'mm/sec^2',
        description:
            'Y-axis acceleration. Used for motion planning to not exceed motor torque and lose steps.',
        inputType: NUMBER,
        min: 1,
        step: 10,
    },
    {
        setting: '$122',
        message: 'Z-axis acceleration',
        category: 'Motors',
        units: 'mm/sec^2',
        description:
            'Z-axis acceleration. Used for motion planning to not exceed motor torque and lose steps.',
        inputType: NUMBER,
        min: 1,
        step: 10,
    },
    {
        setting: '$130',
        message: 'X-axis maximum travel',
        category: 'Limits',
        units: 'mm',
        description:
            'Maximum X-axis travel distance from homing switch. Determines valid machine space for soft-limits and homing search distances.',
        inputType: NUMBER,
        min: 1,
        step: 10,
    },
    {
        setting: '$131',
        message: 'Y-axis maximum travel',
        category: 'Limits',
        units: 'mm',
        description:
            'Maximum Y-axis travel distance from homing switch. Determines valid machine space for soft-limits and homing search distances.',
        inputType: NUMBER,
        min: 1,
        step: 10,
    },
    {
        setting: '$132',
        message: 'Z-axis maximum travel',
        category: 'Limits',
        units: 'mm',
        description:
            'Maximum Z-axis travel distance from homing switch. Determines valid machine space for soft-limits and homing search distances.',
        inputType: NUMBER,
        min: 1,
        step: 10,
    },
];
