import defaultState from 'app/store/defaultState';
import Generator from '../utils/surfacingGcodeGenerator';
import { IMPERIAL_UNITS, METRIC_UNITS } from 'app/constants';

describe('Surfacing Output', () => {
    it('should generate gcode for surfacing', () => {
        const gcodeGenerator = new Generator({
            surfacing: defaultState.widgets.surfacing,
            units: 'mm',
        });
        const gcode = gcodeGenerator.generate();
        expect(gcode).toBeDefined();
    });
    it('should generate gcode for surfacing with imperial units', () => {
        const gcodeGenerator = new Generator({
            surfacing: defaultState.widgets.surfacing,
            units: IMPERIAL_UNITS,
        });
        const gcode = gcodeGenerator.generate();
        expect(gcode).toMatch(/G20/);
    });
    it('should generate gcode for surfacing with metric units', () => {
        const gcodeGenerator = new Generator({
            surfacing: defaultState.widgets.surfacing,
            units: METRIC_UNITS,
        });
        const gcode = gcodeGenerator.generate();
        expect(gcode).toMatch(/G21/);
    });
    it('should output the correct gcode for the surfacing', () => {
        const gcodeGenerator = new Generator({
            surfacing: defaultState.widgets.surfacing,
            units: METRIC_UNITS,
        });

        const gcode = gcodeGenerator.generate({ returnArray: true });

        expect(gcode).toEqual(
            expect.arrayContaining([
                '(Header)',
                '(Generated by gSender from Sienci Labs)',
                'G21 ;mm',
                'G90',
                'M3 S17000',
                'G0 X0 Y0',
                'G0 Z3',
                'G1 F2500',
                '(Header End)',
                '',
                '',
                '(*** Layer 1 ***)',
                '(Covering Surfacing Perimeter)',
                '(Ramping into Material)',
                'G91',
                'G1 X28.36 Z-4',
                'G1 X5',
                'G1 X-33.36',
                'G90',
                '(End of Ramping into Material)',
                '',
                'G1 Y-100',
                'G1 X100',
                'G1 Y0',
                'G1 X0',
                '(End of Covering Surfacing Perimeter)',
                '',
                '(Entering Start Position)',
                'G91',
                'G1 Y-8.8',
                'G1 X8.8',
                'G90',
                '(End of Entering Start Position)',
                '',
                'G1 Y-91.2',
                'G1 X91.2',
                'G1 Y-8.8',
                'G1 X17.6',
                '',
                'G1 Y-82.4',
                'G1 X82.4',
                'G1 Y-17.6',
                'G1 X26.4',
                '',
                'G1 Y-73.6',
                'G1 X73.6',
                'G1 Y-26.4',
                'G1 X35.2',
                '',
                'G1 Y-64.8',
                'G1 X64.8',
                'G1 Y-35.2',
                'G1 X44',
                '',
                'G1 Y-56',
                'G1 X56',
                'G1 Y-44',
                'G1 X52.8',
                '',
                'G1 Y-47.2',
                '',
                '(Returning to Zero)',
                'G0 Z3',
                'G0 X0 Y0',
                '(End of Returning to Zero)',
                '',
                '(*** End of Layer 1 ***)',
                '',
                '',
                '(Footer)',
                'M5 ;Turn off spindle',
                '(End of Footer)',
            ]),
        );
    });
});
