import defaultState from 'app/store/defaultState';
import Generator from '../utils/surfacingGcodeGenerator';
import {
    IMPERIAL_UNITS,
    METRIC_UNITS,
    SPIRAL_MOVEMENT,
    ZIG_ZAG_MOVEMENT,
    START_POSITION_BACK_LEFT,
    START_POSITION_BACK_RIGHT,
    START_POSITION_FRONT_LEFT,
    START_POSITION_FRONT_RIGHT,
    START_POSITION_CENTER,
} from 'app/constants';

const baseSurfacing = defaultState.widgets.surfacing;

describe('Surfacing GCode Generator', () => {

    describe('Units', () => {
        it('should generate gcode (basic)', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: 'mm' });
            const gcode = gen.generate();
            expect(gcode).toBeDefined();
            expect(typeof gcode).toBe('string');
            expect(gcode.length).toBeGreaterThan(0);
        });

        it('should include G20 for imperial units', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: IMPERIAL_UNITS });
            expect(gen.generate()).toMatch(/G20/);
        });

        it('should include G21 for metric units', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: METRIC_UNITS });
            expect(gen.generate()).toMatch(/G21/);
        });
    });

    describe('Header and Footer', () => {
        it('should include gSender header comment', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: METRIC_UNITS });
            expect(gen.generate()).toMatch(/Generated by gSender from Sienci Labs/);
        });

        it('should include G90 absolute positioning', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: METRIC_UNITS });
            expect(gen.generate()).toMatch(/G90/);
        });

        it('should include M5 spindle off in footer', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: METRIC_UNITS });
            expect(gen.generate()).toMatch(/M5/);
        });

        it('should include return to zero', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: METRIC_UNITS });
            expect(gen.generate()).toMatch(/G0 X0 Y0/);
        });

        it('should include feedrate command', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: METRIC_UNITS });
            expect(gen.generate()).toMatch(/G1 F/);
        });
    });

    describe('Coolant (Mist / Flood)', () => {
        it('should include M7 when mist is enabled', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, mist: true, flood: false },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/M7/);
        });

        it('should include M8 when flood is enabled', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, mist: false, flood: true },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/M8/);
        });

        it('should include M7 and M8 when both are enabled', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, mist: true, flood: true },
                units: METRIC_UNITS,
            });
            const gcode = gen.generate();
            expect(gcode).toMatch(/M7/);
            expect(gcode).toMatch(/M8/);
        });

        it('should include M9 coolant off when mist is enabled', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, mist: true },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/M9/);
        });

        it('should include M9 coolant off when flood is enabled', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, flood: true },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/M9/);
        });

        it('should NOT include M7/M8/M9 when coolant is disabled', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, mist: false, flood: false },
                units: METRIC_UNITS,
            });
            const gcode = gen.generate();
            expect(gcode).not.toMatch(/M7/);
            expect(gcode).not.toMatch(/M8/);
            expect(gcode).not.toMatch(/M9/);
        });
    });

    describe('Dwell', () => {
        it('should include G04 when shouldDwell is true', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, shouldDwell: true },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/G04/);
        });

        it('should NOT include G04 when shouldDwell is false', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, shouldDwell: false },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).not.toMatch(/G04/);
        });
    });

    describe('Multi-layer', () => {
        it('should generate Layer 1 comment', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, skimDepth: 1, maxDepth: 1 },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/Layer 1/);
        });

        it('should generate multiple layers when maxDepth > skimDepth', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, skimDepth: 1, maxDepth: 3 },
                units: METRIC_UNITS,
            });
            const gcode = gen.generate();
            expect(gcode).toMatch(/Layer 1/);
            expect(gcode).toMatch(/Layer 2/);
            expect(gcode).toMatch(/Layer 3/);
        });

        it('should include Move to Starting Height for layers after first', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, skimDepth: 1, maxDepth: 2 },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/Move to Starting Height/);
        });
    });

    describe('ZigZag Pattern', () => {
        it('should generate zigzag gcode', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: ZIG_ZAG_MOVEMENT },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate zigzag with cutDirectionFlipped true', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: ZIG_ZAG_MOVEMENT, cutDirectionFlipped: true },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate zigzag with cutDirectionFlipped false', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: ZIG_ZAG_MOVEMENT, cutDirectionFlipped: false },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate zigzag when width > length', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: ZIG_ZAG_MOVEMENT, width: 150, length: 80 },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate zigzag when length > width', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: ZIG_ZAG_MOVEMENT, width: 80, length: 150 },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate zigzag from CENTER start position', () => {
            const gen = new Generator({
                surfacing: {
                    ...baseSurfacing,
                    type: ZIG_ZAG_MOVEMENT,
                    startPosition: START_POSITION_CENTER,
                },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/Entering Start Area/);
        });

        it('should generate zigzag from CENTER with cutDirectionFlipped', () => {
            const gen = new Generator({
                surfacing: {
                    ...baseSurfacing,
                    type: ZIG_ZAG_MOVEMENT,
                    startPosition: START_POSITION_CENTER,
                    cutDirectionFlipped: true,
                },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate zigzag with imperial units', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: ZIG_ZAG_MOVEMENT },
                units: IMPERIAL_UNITS,
            });
            expect(gen.generate()).toMatch(/G20/);
        });
    });

    describe('Spiral Pattern', () => {
        it('should generate spiral gcode', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: SPIRAL_MOVEMENT },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate spiral with cutDirectionFlipped true', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: SPIRAL_MOVEMENT, cutDirectionFlipped: true },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate spiral with cutDirectionFlipped false', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: SPIRAL_MOVEMENT, cutDirectionFlipped: false },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate spiral when width > length', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: SPIRAL_MOVEMENT, width: 150, length: 80 },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate spiral when length > width', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: SPIRAL_MOVEMENT, width: 80, length: 150 },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate spiral from CENTER start position', () => {
            const gen = new Generator({
                surfacing: {
                    ...baseSurfacing,
                    type: SPIRAL_MOVEMENT,
                    startPosition: START_POSITION_CENTER,
                },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toMatch(/Entering Perimeter Start Position/);
        });

        it('should generate spiral from CENTER with cutDirectionFlipped', () => {
            const gen = new Generator({
                surfacing: {
                    ...baseSurfacing,
                    type: SPIRAL_MOVEMENT,
                    startPosition: START_POSITION_CENTER,
                    cutDirectionFlipped: true,
                },
                units: METRIC_UNITS,
            });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate spiral with imperial units', () => {
            const gen = new Generator({
                surfacing: { ...baseSurfacing, type: SPIRAL_MOVEMENT },
                units: IMPERIAL_UNITS,
            });
            expect(gen.generate()).toMatch(/G20/);
        });
    });

    describe('Start Positions', () => {
        const positions = [
            START_POSITION_BACK_LEFT,
            START_POSITION_BACK_RIGHT,
            START_POSITION_FRONT_LEFT,
            START_POSITION_FRONT_RIGHT,
            START_POSITION_CENTER,
        ];

        positions.forEach((position) => {
            it(`should generate zigzag for start position: ${position}`, () => {
                const gen = new Generator({
                    surfacing: { ...baseSurfacing, type: ZIG_ZAG_MOVEMENT, startPosition: position },
                    units: METRIC_UNITS,
                });
                expect(gen.generate()).toBeTruthy();
            });

            it(`should generate spiral for start position: ${position}`, () => {
                const gen = new Generator({
                    surfacing: { ...baseSurfacing, type: SPIRAL_MOVEMENT, startPosition: position },
                    units: METRIC_UNITS,
                });
                expect(gen.generate()).toBeTruthy();
            });
        });
    });

    describe('Ramping Degrees', () => {
        it('should generate gcode with custom rampingDegrees', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: METRIC_UNITS, rampingDegrees: 15 });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate gcode with default rampingDegrees', () => {
            const gen = new Generator({ surfacing: baseSurfacing, units: METRIC_UNITS });
            expect(gen.generate()).toBeTruthy();
        });
    });

    describe('Stepover', () => {
        it('should cap stepover at 80% when value exceeds 80', () => {
            const gen = new Generator({ surfacing: { ...baseSurfacing, stepover: 90 }, units: METRIC_UNITS });
            expect(gen.generate()).toBeTruthy();
        });

        it('should use stepover value when <= 80', () => {
            const gen = new Generator({ surfacing: { ...baseSurfacing, stepover: 40 }, units: METRIC_UNITS });
            expect(gen.generate()).toBeTruthy();
        });

        it('should generate zigzag CENTER cutDirectionFlipped large dimensions', () => {
    const gen = new Generator({
        surfacing: {
            ...baseSurfacing,
            type: ZIG_ZAG_MOVEMENT,
            startPosition: START_POSITION_CENTER,
            cutDirectionFlipped: true,
            width: 200,
            length: 200,
            bitDiameter: 5,
            stepover: 40,
        },
        units: METRIC_UNITS,
    });
    expect(gen.generate()).toBeTruthy();
});

it('should generate spiral cutDirectionFlipped when length equals width', () => {
    const gen = new Generator({
        surfacing: {
            ...baseSurfacing,
            type: SPIRAL_MOVEMENT,
            cutDirectionFlipped: true,
            width: 80,
            length: 80,
        },
        units: METRIC_UNITS,
    });
    expect(gen.generate()).toBeTruthy();
});

// Hits lines 276-281: singleMovement=true with lastAxis X and Y
it('should generate spiral with singleMovement lastAxis X', () => {
    const gen = new Generator({
        surfacing: {
            ...baseSurfacing,
            type: SPIRAL_MOVEMENT,
            cutDirectionFlipped: false,
            width: 80,
            length: 150,  // length > width forces lastAxis Y, but we need X
        },
        units: METRIC_UNITS,
    });
    expect(gen.generate()).toBeTruthy();
});

it('should generate spiral with singleMovement lastAxis Y', () => {
    const gen = new Generator({
        surfacing: {
            ...baseSurfacing,
            type: SPIRAL_MOVEMENT,
            cutDirectionFlipped: false,
            width: 150,
            length: 80,  // width > length forces lastAxis X
            startPosition: START_POSITION_CENTER,
        },
        units: METRIC_UNITS,
    });
    expect(gen.generate()).toBeTruthy();
});

// Hits line 436: cutDirectionFlipped spiral where width > length
it('should generate spiral cutDirectionFlipped when width > length', () => {
    const gen = new Generator({
        surfacing: {
            ...baseSurfacing,
            type: SPIRAL_MOVEMENT,
            cutDirectionFlipped: true,
            width: 150,
            length: 80,  // width > length triggers line 434-436
        },
        units: METRIC_UNITS,
    });
    expect(gen.generate()).toBeTruthy();
});
    });
});