export default [
    // Sienci Labs
    {
        id: 0,
        company: 'Sienci Labs',
        name: 'Mill One',
        type: 'V1',
        width: 234,
        units: 'mm',
        depth: 185,
        height: 90,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 1,
        company: 'Sienci Labs',
        name: 'Mill One',
        type: 'V2',
        width: 234,
        units: 'mm',
        depth: 185,
        height: 90,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 2,
        company: 'Sienci Labs',
        name: 'Mill One',
        type: 'V3',
        width: 258,
        units: 'mm',
        depth: 185,
        height: 90,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 3,
        company: 'Sienci Labs',
        name: 'LongMill',
        type: '12x12',
        width: 307,
        units: 'mm',
        depth: 345,
        height: 114.3,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 4,
        company: 'Sienci Labs',
        name: 'LongMill',
        type: '12x30',
        width: 792,
        units: 'mm',
        depth: 345,
        height: 114.3,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 5,
        company: 'Sienci Labs',
        name: 'LongMill',
        type: '30x30',
        width: 792,
        units: 'mm',
        depth: 845,
        height: 114.3,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    // Carbide 3D
    {
        id: 6,
        company: 'Carbide 3D',
        name: 'Shapeoko',
        type: '2',
        width: 304,
        units: 'mm',
        depth: 304.8,
        height: 63.5,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 7,
        company: 'Carbide 3D',
        name: 'Shapeoko',
        type: '3',
        width: 406.4,
        units: 'mm',
        depth: 406.4,
        height: 76.2,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 8,
        company: 'Carbide 3D',
        name: 'Shapeoko',
        type: 'XL',
        width: 812.8,
        units: 'mm',
        depth: 406.4,
        height: 76.2,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 9,
        company: 'Carbide 3D',
        name: 'Shapeoko',
        type: 'XXL',
        width: 812.8,
        units: 'mm',
        depth: 838.2,
        height: 76.2,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 10,
        company: 'Carbide 3D',
        name: 'Shapeoko',
        type: 'Pro XL',
        width: 838.2,
        units: 'mm',
        depth: 444.5,
        height: 101.6,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 11,
        company: 'Carbide 3D',
        name: 'Shapeoko',
        type: 'Pro XXL',
        width: 838.2,
        units: 'mm',
        depth: 838.2,
        height: 101.6,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 12,
        company: 'Carbide 3D',
        name: 'Nomad',
        type: '883',
        width: 203.2,
        units: 'mm',
        depth: 203.2,
        height: 76.2,
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false
    },
    {
        id: 13,
        company: 'Carbide 3D',
        name: 'Nomad',
        type: '883 Pro',
        width: 203.2,
        units: 'mm',
        depth: 203.2,
        height: 76.2,
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false
    },
    {
        id: 14,
        company: 'Carbide 3D',
        name: 'Nomad',
        type: '3',
        width: 203.2,
        units: 'mm',
        depth: 203.2,
        height: 76.2,
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false
    },
    // Inventables
    {
        id: 15,
        company: 'Inventables',
        name: 'XCarve',
        type: '500mm',
        width: 250,
        units: 'mm',
        depth: 250,
        height: 65,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 16,
        company: 'Inventables',
        name: 'XCarve',
        type: '750mm',
        width: 500,
        units: 'mm',
        depth: 500,
        height: 65,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 17,
        company: 'Inventables',
        name: 'XCarve',
        type: '1000mm',
        width: 750,
        units: 'mm',
        depth: 750,
        height: 65,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 18,
        company: 'Inventables',
        name: 'XCarve',
        type: 'Pro 4x2',
        width: 1219.2,
        units: 'mm',
        depth: 609.6,
        height: 101.6,
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false
    },
    {
        id: 19,
        company: 'Inventables',
        name: 'XCarve',
        type: 'Pro 4x4',
        width: 1219.2,
        units: 'mm',
        depth: 1219.2,
        height: 101.6,
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false
    },
    {
        id: 20,
        company: 'Inventables',
        name: 'Carvey',
        type: '',
        width: 294.64,
        units: 'mm',
        depth: 203.2,
        height: 63.5,
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false
    },
    // Kibre Enterprises
    {
        id: 21,
        company: 'Kibre Enterprises',
        name: 'Onefinity',
        type: 'Machinist',
        width: 412.75,
        units: 'mm',
        depth: 412.75,
        height: 113.35,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 22,
        company: 'Kibre Enterprises',
        name: 'Onefinity',
        type: 'Woodworker',
        width: 819.15,
        units: 'mm',
        depth: 819.15,
        height: 113.35,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    // OpenBuilds
    {
        id: 23,
        company: 'OpenBuilds',
        name: 'C-Beam',
        type: '',
        width: 270,
        units: 'mm',
        depth: 270,
        height: 80,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 24,
        company: 'OpenBuilds',
        name: 'C-Beam',
        type: 'XLarge',
        width: 750,
        units: 'mm',
        depth: 330,
        height: 63.5,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 25,
        company: 'OpenBuilds',
        name: 'Lead',
        type: '1010',
        width: 810,
        units: 'mm',
        depth: 730,
        height: 90,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 26,
        company: 'OpenBuilds',
        name: 'Lead',
        type: '1515',
        width: 1170,
        units: 'mm',
        depth: 1250,
        height: 90,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 27,
        company: 'OpenBuilds',
        name: 'MiniMill',
        type: '',
        width: 120,
        units: 'mm',
        depth: 120,
        height: 60,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 28,
        company: 'OpenBuilds',
        name: 'Sphinx',
        type: '55',
        width: 333,
        units: 'mm',
        depth: 325,
        height: 85,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 29,
        company: 'OpenBuilds',
        name: 'Sphinx',
        type: '1050',
        width: 833.5,
        units: 'mm',
        depth: 325,
        height: 85,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 30,
        company: 'OpenBuilds',
        name: 'WorkBee',
        type: '1010',
        width: 824,
        units: 'mm',
        depth: 780,
        height: 122,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 31,
        company: 'OpenBuilds',
        name: 'WorkBee',
        type: '1050',
        width: 317,
        units: 'mm',
        depth: 762,
        height: 122,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 32,
        company: 'OpenBuilds',
        name: 'WorkBee',
        type: '1510',
        width: 824,
        units: 'mm',
        depth: 1280,
        height: 122,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    // Ooznest
    {
        id: 33,
        company: 'Ooznest',
        name: 'WorkBee',
        type: '',
        width: 300,
        units: 'mm',
        depth: 270,
        height: 47,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    // Mill Right
    {
        id: 34,
        company: 'Mill Right',
        name: 'M3',
        type: '',
        width: 260,
        units: 'mm',
        depth: 260,
        height: 50,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 35,
        company: 'Mill Right',
        name: 'Carve King',
        type: '1',
        width: 438.15,
        units: 'mm',
        depth: 438.15,
        height: 101.6,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 36,
        company: 'Mill Right',
        name: 'Carve King',
        type: '2',
        width: 438.15,
        units: 'mm',
        depth: 438.15,
        height: 101.6,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 37,
        company: 'Mill Right',
        name: 'Mega V',
        type: '',
        width: 482.6,
        units: 'mm',
        depth: 482.6,
        height: 95.25,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 38,
        company: 'Mill Right',
        name: 'Mega V',
        type: 'XL',
        width: 889,
        units: 'mm',
        depth: 889,
        height: 95.25,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 39,
        company: 'Mill Right',
        name: 'Power Route',
        type: '',
        width: 635,
        units: 'mm',
        depth: 635,
        height: 127,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 40,
        company: 'Mill Right',
        name: 'Power Route',
        type: 'XL',
        width: 1257.3,
        units: 'mm',
        depth: 1257.3,
        height: 127,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    // CNC4newbie
    {
        id: 41,
        company: 'CNC4newbie',
        name: 'New-Carve',
        type: '',
        width: 400.05,
        units: 'mm',
        depth: 368.3,
        height: 177.8,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 42,
        company: 'CNC4newbie',
        name: 'C4N48xx',
        type: '',
        width: 1270,
        units: 'mm',
        depth: 660.4,
        height: 177.8,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    // BobsCNC
    {
        id: 43,
        company: 'BobsCNC',
        name: 'EV3',
        type: '',
        width: 457.2,
        units: 'mm',
        depth: 406.4,
        height: 83.82,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 44,
        company: 'BobsCNC',
        name: 'EV4',
        type: '',
        width: 609.6,
        units: 'mm',
        depth: 609.6,
        height: 83.82,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 45,
        company: 'BobsCNC',
        name: 'KL733',
        type: '',
        width: 914.4,
        units: 'mm',
        depth: 914.4,
        height: 127,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 46,
        company: 'BobsCNC',
        name: 'KL744',
        type: '',
        width: 1219.2,
        units: 'mm',
        depth: 1219.2,
        height: 127,
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false
    },
    // SainSmart
    {
        id: 47,
        company: 'SainSmart',
        name: 'Genmitsu',
        type: '1810',
        width: 180,
        units: 'mm',
        depth: 100,
        height: 45,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 48,
        company: 'SainSmart',
        name: 'Genmitsu',
        type: '3018',
        width: 300,
        units: 'mm',
        depth: 180,
        height: 45,
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false
    },
    {
        id: 49,
        company: 'SainSmart',
        name: 'Genmitsu',
        type: 'PROVerXL 4030',
        width: 400,
        units: 'mm',
        depth: 300,
        height: 110,
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false
    },
];
