export const UPDATE_PRESET = 'UPDATE_PRESET';

export const UPDATE_JOG = 'UPDATE_JOG';

export const SET_ACTIVE_DIALOG = 'SET_ACTIVE_DIALOG';

export const CLOSE_ACTIVE_DIALOG = 'CLOSE_ACTIVE_DIALOG';

export const UPDATE_PHYSICAL_UNIT_SETUP = 'UPDATE_PHYSICAL_UNIT_SETUP';

export const SET_STOCK_TURNING_OUTPUT = 'SET_STOCK_TURNING_OUTPUT';

export const UPDATE_STOCK_TURNING_OPTION = 'UPDATE_STOCK_TURNING_OPTION';

export const CONVERT_STOCK_TURNING_OPTIONS_TO_IMPERIAL =
    'CONVERT_STOCK_TURNING_OPTIONS_TO_IMPERIAL';

export const CONVERT_STOCK_TURNING_OPTIONS_TO_METRIC =
    'CONVERT_STOCK_TURNING_OPTIONS_TO_METRIC';

export const SET_ACTIVE_STOCK_TURNING_TAB = 'SET_ACTIVE_STOCK_TURNING_TAB';
