declare module 'universal-logger';
declare module 'universal-logger-browser';
declare module 'gcode-parser';
declare module 'memoize-one';
declare module 'gamepad.js';
declare module 'gcode-interpreter';
declare module 'classnames';
// declare module '@tanstack/react-router';
declare module 'react-select';
declare module 'chained-function';
declare module 'ensure-array';
declare module 'uuid/v4';
