// declare module 'lodash';
// declare module 'lodash/isEmpty';
// declare module 'lodash/get';
// declare module 'lodash/partition';
// declare module 'lodash/uniqueId';
// declare module 'file-saver';
// declare module 'mousetrap';
// declare module 'events';
declare module 'universal-logger';
declare module 'universal-logger-browser';
declare module 'gcode-parser';
// declare module 'sha1';
// declare module 'react-dom';
// declare module 'pubsub-js';
// declare module 'three';
// declare module 'memoize-one';
declare module 'gamepad.js';
// declare module 'objtools';
declare module 'gcode-interpreter';