export const MODALS = {
    STOCK_TURNING: 'STOCK_TURNING',
    PHYSICAL_UNIT_SETUP: 'PHYSICAL_UNIT_SETUP',
};

export const A_AXIS_JOG = '5.00';

export const DRILL_BIT_DIAMETER = {
    QUARTER: '1/4',
    EIGHTH: '1/8',
};

export const HOLE_COUNT = {
    SIX: 6,
    TEN: 10,
    TWO: 2,
};

export const Z_AXIS_PROBING_MACRO = `
    %PROBE_FAST_FEEDRATE = 150
    %PROBE_SLOW_FEEDRATE = 50
    %PROBE_RETRACTION = 1
    G91 ; Relative positioning
    G21 ;Use millimeters=
    G38.2 Z-30 F[PROBE_FAST_FEEDRATE]
    G0 Z[PROBE_RETRACTION ]
    G38.2 Z-2 F[PROBE_SLOW_FEEDRATE]
    G4 P0.15
    G10 L20 P0 Z39
    G0 Z3
    G90
`;

export const Y_AXIS_ALIGNMENT_PROBING_MACRO = `
    %PROBE_FAST_FEEDRATE = 150
    %PROBE_SLOW_FEEDRATE = 50
    %PROBE_RETRACTION = 1
    %CLEARANCE_HEIGHT = 5
    %PROBE_HEIGHT = -3

    G91 ; Relative positioning
    G21 ;Use millimeters
    G38.2 Z-30 F[PROBE_FAST_FEEDRATE]
    G4 P0.15
    G0 Z[CLEARANCE_HEIGHT]
    G0 Y32
    G0 Z[-CLEARANCE_HEIGHT+PROBE_HEIGHT]
    G38.2 Y-32 F[PROBE_FAST_FEEDRATE]
    G0 Y[PROBE_RETRACTION]
    G38.2 Y-2 F[PROBE_SLOW_FEEDRATE]
    G4 P0.15
    %REAR_SEEK_POS = [posy]
    G0 Y[PROBE_RETRACTION]
    G0 Z[CLEARANCE_HEIGHT-PROBE_HEIGHT]
    G0 Y-44
    G0 Z[-CLEARANCE_HEIGHT+PROBE_HEIGHT]
    G38.2 Y32 F[PROBE_FAST_FEEDRATE]
    G0 Y[-PROBE_RETRACTION]
    G38.2 Y2 F[PROBE_SLOW_FEEDRATE]
    G4 P0.15
    %FRONT_SEEK_POS = [posy]
    G0 Y[-PROBE_RETRACTION]
    G0 Z[CLEARANCE_HEIGHT-PROBE_HEIGHT]
    %Y_SEEK_CENTERDIST = [REAR_SEEK_POS - FRONT_SEEK_POS]
    G0 Y[PROBE_RETRACTION+Y_SEEK_CENTERDIST/2]
    G10 L20 Y0
    G38.2 Z[-CLEARANCE_HEIGHT+PROBE_HEIGHT] F[PROBE_FAST_FEEDRATE]
    G0 Z[PROBE_RETRACTION]
    G38.2 Z-2 F[PROBE_SLOW_FEEDRATE]
    G4 P0.15
    G10 L20 Z39
    G0 Z3
    G90
`;
