/*
 * Copyright (C) 2021 Sienci Labs Inc.
 *
 * This file is part of gSender.
 *
 * gSender is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, under version 3 of the License.
 *
 * gSender is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with gSender.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Contact for information regarding this program and its license
 * can be sent through gSender@sienci.com or mailed to the main office
 * of Sienci Labs Inc. in Waterloo, Ontario, Canada.
 *
 */

import { SLB_DEFAULT } from 'app/config/eeprom/SLB';
import * as longMillGrblEEPROM from 'app/config/eeprom/grbl/longmill';
import * as longMillGrblHALEEPROM from 'app/config/eeprom/grblHAL/longmill';
import * as millOneGrblEEPROM from 'app/config/eeprom/grbl/millone';
import * as altmillSettings from 'app/config/eeprom/altmill';

export default [
    {
        id: 0,
        company: 'Sienci Labs',
        name: 'LongMill MK2',
        type: '30x30',
        version: 'MK2',
        mm: {
            width: 792,
            depth: 845,
            height: 114.3,
        },
        in: {
            width: 31.18,
            depth: 33.27,
            height: 4.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: longMillGrblEEPROM.LONGMILL_MK2_30x30,
        grblHALeepromSettings: longMillGrblHALEEPROM.LONGMILL_MK2_30x30,
    },
    {
        id: 1,
        company: 'Sienci Labs',
        name: 'LongMill MK2',
        type: '48x30',
        version: 'MK2',
        mm: {
            width: 1279.9,
            depth: 845,
            height: 114.3,
        },
        in: {
            width: 50.39,
            depth: 33.27,
            height: 4.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        eepromSettings: longMillGrblEEPROM.LONGMILL_MK2_48x30,
        grblHALeepromSettings: longMillGrblHALEEPROM.LONGMILL_MK2_48x30,
    },
    {
        id: 2,
        company: 'Sienci Labs',
        name: 'LongMill MK2',
        type: '12x30',
        version: 'MK2',
        mm: {
            width: 792,
            depth: 345,
            height: 114.3,
        },
        in: {
            width: 31.18,
            depth: 13.58,
            height: 4.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: longMillGrblEEPROM.LONGMILL_MK2_12x30,
        grblHALeepromSettings: longMillGrblHALEEPROM.LONGMILL_MK2_12x30,
    },
    {
        id: 7,
        company: 'Sienci Labs',
        name: 'Mill One',
        type: 'V1',
        version: 'MK1',
        mm: {
            width: 234,
            depth: 185,
            height: 90,
        },
        in: {
            width: 9.21,
            depth: 7.28,
            height: 3.54,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: millOneGrblEEPROM.MILL_ONE_V1_AND_V2,
    },
    {
        id: 8,
        company: 'Sienci Labs',
        name: 'Mill One',
        type: 'V2',
        version: 'MK1',
        mm: {
            width: 234,
            depth: 185,
            height: 90,
        },
        in: {
            width: 9.21,
            depth: 7.28,
            height: 3.54,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: millOneGrblEEPROM.MILL_ONE_V1_AND_V2,
    },
    {
        id: 9,
        company: 'Sienci Labs',
        name: 'Mill One',
        type: 'V3',
        version: 'MK1',
        mm: {
            width: 258,
            depth: 185,
            height: 90,
        },
        in: {
            width: 10.16,
            depth: 7.28,
            height: 3.54,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: millOneGrblEEPROM.MILL_ONE_V3,
    },
    {
        id: 3,
        company: 'Sienci Labs',
        name: 'LongMill MK1',
        type: '12x12',
        version: 'MK1',
        mm: {
            width: 307,
            depth: 345,
            height: 114.3,
        },
        in: {
            width: 12.09,
            depth: 13.58,
            height: 4.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: longMillGrblEEPROM.LONGMILL_MK1_12x12,
        grblHALeepromSettings: longMillGrblHALEEPROM.LONGMILL_MK1_12x12,
    },
    {
        id: 4,
        company: 'Sienci Labs',
        name: 'LongMill MK1',
        type: '12x30',
        version: 'MK1',
        mm: {
            width: 792,
            depth: 345,
            height: 114.3,
        },
        in: {
            width: 31.18,
            depth: 13.58,
            height: 4.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: longMillGrblEEPROM.LONGMILL_MK1_12x30,
        grblHALeepromSettings: longMillGrblHALEEPROM.LONGMILL_MK1_12x30,
    },
    {
        id: 5,
        company: 'Sienci Labs',
        name: 'LongMill MK1',
        type: '30x30',
        version: 'MK1',
        mm: {
            width: 792,
            depth: 845,
            height: 114.3,
        },
        in: {
            width: 31.18,
            depth: 33.27,
            height: 4.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: longMillGrblEEPROM.LONGMILL_MK1_30x30,
        grblHALeepromSettings: longMillGrblHALEEPROM.LONGMILL_MK1_30x30,
    },
    {
        id: 6,
        company: 'Sienci Labs',
        name: 'LongMill MK1',
        type: '48x30',
        version: 'MK1',
        mm: {
            width: 1279.9,
            depth: 845,
            height: 114.3,
        },
        in: {
            width: 50.39,
            depth: 33.27,
            height: 4.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        eepromSettings: longMillGrblEEPROM.LONGMILL_MK1_48x30,
        grblHALeepromSettings: longMillGrblHALEEPROM.LONGMILL_MK1_48x30,
    },
    {
        id: 10,
        company: '',
        name: 'Shapeoko',
        type: '',
        mm: {
            width: 304,
            depth: 304.8,
            height: 63.5,
        },
        in: {
            width: 11.97,
            depth: 12,
            height: 2.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
    },
    {
        id: 18,
        company: '',
        name: 'X-Carve',
        type: '',
        mm: {
            width: 1219.2,
            depth: 609.6,
            height: 101.6,
        },
        in: {
            width: 48,
            depth: 24,
            height: 4,
        },
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 19,
        company: '',
        name: 'Nomad',
        type: '',
        mm: {
            width: 1219.2,
            depth: 609.6,
            height: 101.6,
        },
        in: {
            width: 48,
            depth: 24,
            height: 4,
        },
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 22,
        company: '',
        name: 'Onefinity',
        type: '',
        mm: {
            width: 819.15,
            depth: 819.15,
            height: 113.35,
        },
        in: {
            width: 32.25,
            depth: 32.25,
            height: 4.46,
        },
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 23,
        company: '',
        name: 'OpenBuilds',
        type: '',
        mm: {
            width: 270,
            depth: 270,
            height: 80,
        },
        in: {
            width: 10.63,
            depth: 10.63,
            height: 3.15,
        },
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 33,
        company: '',
        name: 'Ooznest',
        type: '',
        mm: {
            width: 300,
            depth: 270,
            height: 47,
        },
        in: {
            width: 11.81,
            depth: 10.63,
            height: 1.85,
        },
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 34,
        company: '',
        name: 'MillRight',
        type: '',
        mm: {
            width: 260,
            depth: 260,
            height: 50,
        },
        in: {
            width: 10.24,
            depth: 10.24,
            height: 1.97,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 41,
        company: '',
        name: 'CNC4newbie',
        type: '',
        mm: {
            width: 400.05,
            depth: 368.3,
            height: 177.8,
        },
        in: {
            width: 15.75,
            depth: 14.5,
            height: 7,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 43,
        company: '',
        name: 'BobsCNC',
        type: '',
        mm: {
            width: 457.2,
            depth: 406.4,
            height: 83.82,
        },
        in: {
            width: 18,
            depth: 16,
            height: 3.3,
        },
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 44,
        company: '',
        name: 'YoraHome',
        type: '',
        mm: {
            width: 609.6,
            depth: 609.6,
            height: 90.17,
        },
        in: {
            width: 24,
            depth: 24,
            height: 3.55,
        },
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 47,
        company: '',
        name: 'SainSmart',
        type: '',
        mm: {
            width: 180,
            depth: 100,
            height: 45,
        },
        in: {
            width: 7.09,
            depth: 3.94,
            height: 1.77,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 50,
        company: '',
        name: 'WhittleCNC',
        type: '',
        mm: {
            width: 228,
            depth: 356,
            height: 203,
        },
        in: {
            width: 9,
            depth: 14,
            height: 8,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 51,
        company: '',
        name: 'Evo-One',
        type: '',
        mm: {
            width: 530,
            depth: 450,
            height: 465,
        },
        in: {
            width: 20.8,
            depth: 17.7,
            height: 18.3,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 52,
        company: '',
        name: 'Generic CNC',
        type: '',
        mm: {
            width: 530,
            depth: 450,
            height: 465,
        },
        in: {
            width: 20.8,
            depth: 17.7,
            height: 18.3,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
    },
    {
        id: 53,
        company: 'Sienci Labs',
        name: 'SLB',
        type: '',
        version: '',
        mm: {
            width: 792,
            depth: 845,
            height: 114.3,
        },
        in: {
            width: 31.18,
            depth: 33.27,
            height: 4.5,
        },
        endstops: false,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: SLB_DEFAULT,
        grblHALeepromSettings: SLB_DEFAULT,
        isHal: true,
    },
    {
        id: 54,
        company: 'Sienci Labs',
        name: 'Altmill',
        type: '48X48',
        version: '',
        mm: {
            width: 1260,
            depth: 1248,
            height: 170,
        },
        in: {
            width: 31.18,
            depth: 33.27,
            height: 4.5,
        },
        endstops: true,
        spindle: false,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: altmillSettings.DEFAULT,
        grblHALeepromSettings: altmillSettings.DEFAULT,
        orderedSettings: altmillSettings.ALTMILL_ORDERED,
        isHal: true,
    },
    {
        id: 55,
        company: 'Sienci Labs',
        name: 'Altmill',
        type: '48X48 + Spindle',
        version: '',
        mm: {
            width: 49.6,
            depth: 49.1,
            height: 6.6,
        },
        in: {
            width: 49.6,
            depth: 49.1,
            height: 6.6,
        },
        endstops: true,
        spindle: true,
        coolant: false,
        laser: false,
        laserOnOutline: false,
        eepromSettings: altmillSettings.SPINDLE_KIT,
        grblHALeepromSettings: altmillSettings.SPINDLE_KIT,
        orderedSettings: altmillSettings.SPINDLE_ORDERED,
        isHal: true,
    },
];
