// Data Types for inputs
export const BOOLEAN = 0;
export const BITFIELD = 1;
export const EXCLUSIVE_BITFIELD = 2;
export const RADIO_BUTTON = 3;
export const AXIS_MASK = 4;
export const INTEGER = 5;
export const DECIMAL = 6;
export const STRING = 7;
export const PASSWORD = 8;
export const IPV4 = 9;
