// Data Types for inputs
export const BOOLEAN_ID = 0;
export const BITFIELD_ID = 1;
export const EXCLUSIVE_BITFIELD_ID = 2;
export const RADIO_BUTTON_ID = 3;
export const AXIS_MASK_ID = 4;
export const INTEGER_ID = 5;
export const DECIMAL_ID = 6;
export const STRING_ID = 7;
export const PASSWORD_ID = 8;
export const IPV4_ID = 9;
