export const UPDATE_PRESET = 'UPDATE_PRESET';

export const UPDATE_JOG = 'UPDATE_JOG';

export const SET_ACTIVE_DIALOG = 'SET_ACTIVE_DIALOG';

export const CLOSE_ACTIVE_DIALOG = 'CLOSE_ACTIVE_DIALOG';

export const UPDATE_PHYSICAL_UNIT_SETUP = 'UPDATE_PHYSICAL_UNIT_SETUP';
