name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - dev
      - CI_update
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs: 
  build-debian-pi:
    name: Build Raspberry PI packages
    runs-on: [self-hosted, macOS, ARM64]
    env:
      GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      NODE_OPTIONS: --max-old-space-size=8192
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Environment variables
        run: |
          # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
          echo "• GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "• GITHUB_REF_TYPE=$GITHUB_REF_TYPE" # `branch` or `tag`
          echo "• GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "• GITHUB_SHA=$GITHUB_SHA"
          echo "• RUNNER_ARCH=$RUNNER_ARCH"
          echo "• RUNNER_NAME=$RUNNER_NAME"
          echo "• RUNNER_OS=$RUNNER_OS"
          echo "• RUNNER_TEMP=$RUNNER_TEMP"
          echo "• RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"  
      - name: Build Pi binaries using docker
        shell: bash
        run: |
          scripts/build-pi.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            releases/pi/*
          prerelease: true
          draft: true

 
  