name: Notify on Release in Discord

on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual triggering of the workflow when needed

jobs:
  notify-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Notify on Release in Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_GSENDER_NOTIFICATIONS_WEBHOOK_URL }}
          message: |
            🤖 **A new release has been published:** ${{ github.event.release.tag_name || github.ref_name }}
            
            Link to the release: https://github.com/Sienci-Labs/gsender/releases/tag/${{ github.event.release.tag_name || github.ref_name }}
            
            **Release Notes:**
            ${{ github.event.release.body || 'No release notes provided (Manual Trigger).' }}
