name: Unit Tests

on:
  pull_request:
    branches: [ "test/ci-validation" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: Install Yarn and node-gyp
        run: |
          npm install -g yarn
          yarn global add node-gyp

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test